# -*- coding: utf-8 -*-
"""Aishwarya v k[20221cit0072]07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7qhn-On_r6iTN1oGuwHa9Q009SmdwI5
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/archive.zip"
, index_col=0, na_values=['??','????'])

data.head()

plt.scatter(data['Age'],data1['Price'],c='blue')
plt.title('Scatter PLot')
plt.xlabel('Age (months)')
plt.ylabel('Price (Euros)')
plt.show()

plt.hist(data['KM'], color ='green', edgecolor='white', bins=5)
plt.title('Histogram Plot')
plt.xlabel('Kilometers')
plt.ylabel('Frequency')
plt.show()

counts =[979,120,12]
fueltype = ('Petrol','Diesel','CNG')
index=np.arange(len(fueltype))

plt.bar(index, counts, color=['red', 'blue', 'cyan'])
plt.title('Barplot plot of FuelType')
plt.xlabel('Fuel Type')
plt.ylabel('Frequency')
plt.xticks(index, fueltype,rotation = 90)
plt.show()